from django import forms

class CalculatorForm(forms.Form):
    a11t = forms.IntegerField(label="Основные средства (текущий период)")
    a11p = forms.IntegerField(label="Основные средства (предыдущий период)")
    a12t = forms.IntegerField(label="Отложенные налоговые активы (текущий период)")
    a12p = forms.IntegerField(label="Отложенные налоговые активы (предыдущий период)")
    a13t = forms.IntegerField(label="Финансовые вложения (текущий период)")
    a13p = forms.IntegerField(label="Финансовые вложения (предыдущий период)")
    a14t = forms.IntegerField(label="Прочее (текущий период)")
    a14p = forms.IntegerField(label="Прочее (предыдущий период)")
    a1It = forms.IntegerField(label="Итого раздел I (текущий период)")
    a1Ip = forms.IntegerField(label="Итого раздел I (предыдущий период)")

    a21t = forms.IntegerField(label="Запасы (текущий период)")
    a21p = forms.IntegerField(label="Запасы (предыдущий период)")
    a22t = forms.IntegerField(label="НДС (текущий период)")
    a22p = forms.IntegerField(label="НДС (предыдущий период)")
    a23t = forms.IntegerField(label="Дебиторская задолжность (текущий период)")
    a23p = forms.IntegerField(label="Дебиторская задолжность (предыдущий период)")
    a24t = forms.IntegerField(label="Денежные средства (текущий период)")
    a24p = forms.IntegerField(label="Денежные средства (предыдущий период)")
    a25t = forms.IntegerField(label="Прочее (текущий период)")
    a25p = forms.IntegerField(label="Прочее (предыдущий период)")
    a2It = forms.IntegerField(label="Итого раздел II (текущий период)")
    a2Ip = forms.IntegerField(label="Итого раздел II (предыдущий период)")

    p31t = forms.IntegerField(label="Уставный капитал (текущий период)")
    p31p = forms.IntegerField(label="Уставный капитал (предыдущий период)")
    p32t = forms.IntegerField(label="Добавочный капитал (текущий период)")
    p32p = forms.IntegerField(label="Добавочный капитал (предыдущий период)")
    p33t = forms.IntegerField(label="Резервный капитал (текущий период)")
    p33p = forms.IntegerField(label="Резервный капитал (предыдущий период)")
    p34t = forms.IntegerField(label="Нераспределённая прибыль (текущий период)")
    p34p = forms.IntegerField(label="Нераспределённая прибыль (предыдущий период)")
    p3It = forms.IntegerField(label="Итого раздел III (текущий период)")
    p3Ip = forms.IntegerField(label="Итого раздел III (предыдущий период)")

    p41t = forms.IntegerField(label="Заёмные средства (текущий период)")
    p41p = forms.IntegerField(label="Заёмные средства (предыдущий период)")
    p42t = forms.IntegerField(label="Отложенные налоговые обязательства (текущий период)")
    p42p = forms.IntegerField(label="Отложенные налоговые обязательства (предыдущий период)")
    p4It = forms.IntegerField(label="Итого раздел IV (текущий период)")
    p4Ip = forms.IntegerField(label="Итого раздел IV (предыдущий период)")

    p51t = forms.IntegerField(label="Кредиторская задолжность (текущий период)")
    p51p = forms.IntegerField(label="Кредиторская задолжность (предыдущий период)")
    p52t = forms.IntegerField(label="Оценочные обязательства (текущий период)")
    p52p = forms.IntegerField(label="Оценочные обязательства (предыдущий период)")
    p5It = forms.IntegerField(label="Итого раздел V (текущий период)")
    p5Ip = forms.IntegerField(label="Итого раздел V (предыдущий период)")

    OFR1t = forms.IntegerField(label="Выручка (текущий период)")
    OFR1p = forms.IntegerField(label="Выручка (предыдущий период)")
    OFR2t = forms.IntegerField(label="Себестоимость продаж (текущий период)")
    OFR2p = forms.IntegerField(label="Себестоимость продаж (предыдущий период)")
    OFR3t = forms.IntegerField(label="Валовая приыбль (убыток) (текущий период)")
    OFR3p = forms.IntegerField(label="Валовая приыбль (убыток) (предыдущий период)")
    OFR4t = forms.IntegerField(label="Коммерческие расходы (текущий период)")
    OFR4p = forms.IntegerField(label="Коммерческие расходы (предыдущий период)")
    OFR5t = forms.IntegerField(label="Управленческие расходы (текущий период)")
    OFR5p = forms.IntegerField(label="Управленческие расходы (предыдущий период)")
    OFR6t = forms.IntegerField(label="Прибыль (убыток) от продаж (текущий период)")
    OFR6p = forms.IntegerField(label="Прибыль (убыток) от продаж (предыдущий период)")
    OFR7t = forms.IntegerField(label="Прочие доходы (текущий период)")
    OFR7p = forms.IntegerField(label="Прочие доходы (предыдущий период)")
    OFR8t = forms.IntegerField(label="Прочие расходы (текущий период)")
    OFR8p = forms.IntegerField(label="Прочие расходы (предыдущий период)")
    OFR9t = forms.IntegerField(label="Налог на прибыль организации (текущий период)")
    OFR9p = forms.IntegerField(label="Налог на прибыль организации (предыдущий период)")
    OFR10t = forms.IntegerField(label="Чистая прибыль (текущий период)")
    OFR10p = forms.IntegerField(label="Чистая прибыль (предыдущий период)")